/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_appsync_graphqlEndpoint": "https://f32a6qyzuzewzkco55jximam2u.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  "aws_project_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_MDmq1rUWk",
  "aws_user_pools_web_client_id": "2v76solamuip1474dr4lgll0m8"
  
 
  
  
};



export default awsmobile;