/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
   
  
    aws_project_region: "us-east-1",
    aws_user_pools_id: "us-east-1_8jOlvEoM7",
    aws_user_pools_web_client_id: "3i2vnl090v5lbh9217l1br0nfu"
  
};


export default awsmobile;





// // src/aws-exports.js
// const awsmobile = {
//   aws_project_region: 'us-east-1',
//   aws_cognito_identity_pool_id: 'YOUR_IDENTITY_POOL_ID',
//   aws_cognito_region: 'us-east-1',
//   aws_user_pools_id: 'us-east-1_C3bw1KD8Y',
//   aws_user_pools_web_client_id: '4odvrni8bfva5ou9eohrb1dokp',
//   oauth: {}  // Ensure this is an empty object if you're not using OAuth
// };

// export default awsmobile;